name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  unit:
    name: Unit test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      run: |
        echo "##[set-env name=GOPATH;]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"
      shell: bash
    - name: Verify code formatting
      run: |
        go get golang.org/x/tools/cmd/goimports
        make verify-goimports
      shell: bash
      if: success() && runner.os != 'Windows'
    - name: Build
      run: make build
    - name: Unit test
      run: make coverage
    - name: Verify docs
      run: make verify-docs
    - name: Report coverage
      run: curl -s https://codecov.io/bash | bash -s
      shell: bash
      env:
        CODECOV_TOKEN: d09bee7e-6c5a-4316-a48f-266e08d0f70f

  stage:
    name: Stage
    needs: unit
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      run: |
        echo "##[set-env name=GOPATH]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"
    - name: Stage riff release artifacts
      run: .github/workflows/stage.sh
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}

  acceptance:
    name: Acceptance
    needs: stage
    if: success() && github.event_name == 'push'
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          qualifier: kind
          cluster: kind
          registry: dockerhub
        - os: windows-latest
          qualifier: windows
          cluster: gke
          registry: gcr
      fail-fast: false
    runs-on: ${{ matrix.config.os }}
    env:
      CLUSTER: ${{ matrix.config.cluster }}
      REGISTRY: ${{ matrix.config.registry }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup env
        run: |
          job=$(date +%s) # TODO use something that is assigned by CI to guarantee uniqueness
          echo "JOB_ID=${job}"

          echo "##[set-env name=CLUSTER_NAME]cli-${job}-${{ matrix.config.qualifier }}"
          echo "##[set-env name=NAMESPACE]cli-${job}-${{ matrix.config.qualifier }}"
        shell: bash
      - name: Run acceptance tests
        run: .github/workflows/acceptance.sh
        shell: bash
      - name: Collect diagnostics
        run: .github/workflows/diagnostics.sh
        shell: bash
        if: always()
      - name: Cleanup
        run: .github/workflows/acceptance-cleanup.sh
        shell: bash
        if: always()

  publish:
    name: Publish
    needs: acceptance
    if: |
      success() && 
      github.event_name == 'push' && (
        github.ref == 'refs/heads/master' || (
          startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, 'x')
        )
      )
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish riff release artifacts
      run: .github/workflows/publish.sh ${{ github.ref }}
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
