name: PR
on: [pull_request]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.12'

    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      shell: bash
      run: |
        echo "##[set-env name=GOPATH;]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"

    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Verify code formatting
      run: |
        go get golang.org/x/tools/cmd/goimports
        make verify-goimports
      if: success() && runner.os != 'Windows'

    - name: Build
      run: make build

    - name: Unit test
      run: make coverage

    - name: Verify docs
      run: make verify-docs

    - name: Report coverage
      shell: bash
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: d09bee7e-6c5a-4316-a48f-266e08d0f70f
